services:
  - docker

before_script:
  - ls -lash ~/.ssh/
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - make

deploy:
  - provider: script
    skip_cleanup: true
    script: make publish
    on:
      branch: master
